### ISSUE TITLE
Change the way to handle the Bearer Token

### ISSUE THREAD

**Issue by jlandure** [hgwood/hash-code-2018-qualification#1]
For next year, we can use the `$(gcloud auth application-default print-access-token)` to automatically get a valid token instead of copy/pasting the one taken in the devtools of Chrome 👍 
Perhaps, like (jolicitron)[https://github.com/hgwood/jolicitron], we could create a library to handle this stuff (upload/download)

**Comment by hgwood** [comment]
I don't understand how it works ^^' Can you explain?

**Comment by jlandure** [comment]
I think the command `gcloud auth application-default print-access-token` create a token to talk with the google firewall. I think we can use this to enable auth to discuss with the appengine `judge` application

**Comment by jlandure** [comment]
You have to run this command before `gcloud auth application-default login`

**Comment by hgwood** [comment]
It works! Thanks 👍 

See https://github.com/hgwood/hash-code-2019-qualification/commit/2731d9820b5f19f800ec888f34dcbd2203b78fb3
